import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sonner } from '@/components/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={inter.className}>
        {children}
        {modal}
        <Sonner />
      </body>
    </html>
  )
}
